import {
  Document,
  Page,
  renderToBuffer,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

// Contract template component
function ContractDocument({
  requestCode,
  positionTitle,
  salary,
  currency,
  candidateName,
  candidateEmail,
  candidateAddress,
  startDate,
}: {
  requestCode: string;
  positionTitle: string;
  salary: number;
  currency: string;
  candidateName: string;
  candidateEmail: string;
  candidateAddress?: string;
  startDate: string;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.title}>Employment Contract</Text>
          <Text style={styles.subtitle}>Request Code: {requestCode}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Position Details</Text>
          <Text style={styles.text}>Title: {positionTitle}</Text>
          <Text style={styles.text}>Start Date: {startDate}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Compensation</Text>
          <Text style={styles.text}>
            Salary: {currency} {salary.toLocaleString()}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Candidate Information</Text>
          <Text style={styles.text}>Name: {candidateName}</Text>
          <Text style={styles.text}>Email: {candidateEmail}</Text>
          {candidateAddress && (
            <Text style={styles.text}>Address: {candidateAddress}</Text>
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.footer}>
            This contract is generated by Zenith HR System
          </Text>
        </View>
      </Page>
    </Document>
  );
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
  },
  section: {
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 20,
  },
  heading: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
  },
  text: {
    fontSize: 12,
    marginBottom: 5,
  },
  footer: {
    fontSize: 10,
    color: "#999",
    marginTop: 40,
    textAlign: "center",
  },
});

export async function generateContractPDF(data: {
  requestCode: string;
  positionTitle: string;
  salary: number;
  currency: string;
  candidateName: string;
  candidateEmail: string;
  candidateAddress?: string;
  startDate: string;
}): Promise<Buffer> {
  const doc = (
    <ContractDocument
      candidateAddress={data.candidateAddress}
      candidateEmail={data.candidateEmail}
      candidateName={data.candidateName}
      currency={data.currency}
      positionTitle={data.positionTitle}
      requestCode={data.requestCode}
      salary={data.salary}
      startDate={data.startDate}
    />
  );

  return await renderToBuffer(doc);
}
